### Cloud
GET http://brother.bet/fifaArena?year=2020
### Cloud
GET http://brother.bet/fifaArenaByDate?date=2020.08.19
### Cloud
GET http://brother.bet/fifaArenaDates?year=2020
### Cloud
DELETE http://brother.bet/fifaArena?date=2020.08.19

### Local
GET http://localhost:5000/fifaArena?year=2020
### Local
GET http://localhost:5000/fifaArenaByDate?date=2020.08.19
### Local
GET http://localhost:5000/fifaArenaDates?year=2020
### Local
DELETE http://localhost:5000/fifaArena?date=2020.08.19

