name: Daily update at database
on:
  schedule:
    - cron: '1 0 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://brother-bet-mobile.vercel.app/api/fifa_arena' \
